apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: frontend-app
spec:
  template:
    metadata:
      annotations:  
        dapr.io/app-id: frontend-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true" 
        dapr.io/metrics-port: "9092"
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containerConcurrency: 0
      containers:
        - image: ko://github.com/salaboy/dapr-testcontainers/frontend-app
          name: user-container
          livenessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
          readinessProbe:
            httpGet:
              path: /health/liveness
              port: 8080