apiVersion: v2
description: A Helm chart for the App
name: java-app
version: v0.1.0
type: application
icon: https://salaboy.files.wordpress.com/2019/07/avatar.png
appVersion: v0.1.0
maintainers: 
  - name: salaboy
    email: salaboy@gmail.com
    url: http://salaboy.com
home: http://github.com/salaboy/prototype-apps    
keywords:
  - cloudnative
  - example
  - cd
  - kubernetes
  - tutorial